// Generated by CoffeeScript 1.12.2
var Cursor, Utils;

Utils = require('./utils');

Cursor = (function() {
  function Cursor(opts) {
    this.position = {
      x: 0,
      y: 0
    };
    this.offset = 0;
  }

  Cursor.prototype.draw = function(ctx, offset, opts) {
    var height, i, j, ref, results, shade, shades, width;
    this.defaults = {
      color: 'rgb(96, 192, 64)',
      height: 400,
      width: 2
    };
    this.opts = Utils.merge(this.defaults, opts);
    if (offset !== void 0) {
      this.offset = offset;
    }
    ctx.strokeStyle = this.opts.color;
    ctx.lineWidth = this.opts.width;
    ctx.beginPath();
    ctx.moveTo(this.offset + this.position.x, 0);
    ctx.lineTo(this.offset + this.position.x, ctx.canvas.height);
    ctx.closePath();
    ctx.stroke();
    i = 0;
    shades = [140, 163, 184, 201, 217, 229, 240, 247, 252];
    width = ctx.canvas.width;
    height = ctx.canvas.height;
    results = [];
    for (i = j = 0, ref = shades.length; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      shade = 1 - (shades[i] / 255);
      shade = "rgba(0, 0, 0, " + shade + ")";
      ctx.fillStyle = shade;
      ctx.fillRect(0, i, width, 1);
      ctx.fillRect(0, height - i + 1, width, 1);
      ctx.fillRect(i, 0, 1, height);
      results.push(ctx.fillRect(width - i + 1, 0, 1, height));
    }
    return results;
  };

  Cursor.prototype.update = function(ctx) {};

  return Cursor;

})();

module.exports = Cursor;

//# sourceMappingURL=cursor.js.map
