// Generated by CoffeeScript 1.12.2
var Cursor, Utils;

Utils = require('./utils');

Cursor = (function() {
  Cursor.prototype.defaults = {
    color: 'rgb(96, 192, 64)',
    height: 400,
    width: 2
  };

  Cursor.prototype.position = {
    x: 0,
    y: 0
  };

  function Cursor(ctx, opts) {
    this.ctx = ctx;
    this.opts = Utils.merge(this.defaults, opts);
  }

  Cursor.prototype.draw = function() {};

  Cursor.prototype.update = function() {};

  return Cursor;

})();

module.exports = Cursor;

//# sourceMappingURL=cursor.js.map
