// Generated by CoffeeScript 1.12.2
var Graph, Utils;

Utils = require('./utils');

Graph = (function() {
  Graph.prototype.defaults = {
    background: '#313131',
    font: '13px Verdana',
    fontColor: '#ccc'
  };

  function Graph(ctx, opts) {
    this.ctx = ctx;
    this.opts = Utils.merge(this.defaults, opts);
  }

  Graph.prototype.draw = function() {};

  Graph.prototype.update = function() {};

  return Graph;

})();

module.exports = Graph;

//# sourceMappingURL=graph.js.map
