// Generated by CoffeeScript 1.12.2
var Cursor, Graph, Timeline;

Graph = require('./graph');

Cursor = require('./cursor');

Timeline = (function() {
  function Timeline() {
    this.defaults = {
      width: window.innerWidth,
      height: window.innerHeight
    };
    this.canvas = window.document.getElementById('timeline');
    this.ctx = this.canvas.getContext('2d');
    $((function(_this) {
      return function() {
        _this.canvas.width = $('#entities_list').width();
        _this.canvas.height = $('#entities_list').height();
        _this.graph = new Graph();
        _this.cursor = new Cursor();
        _this.graph.draw(_this.ctx);
        _this.cursor.draw(_this.ctx);
        return _this.listenEvents(_this.ctx, _this.graph, _this.cursor);
      };
    })(this));
  }

  Timeline.prototype.listenEvents = function(ctx, graph, cursor) {
    var onMouseDown, onMouseMoveCursor, onMouseMoveGraph, onMouseUp, onMouseWheel, onResize, startX, startY;
    startX = 0;
    startY = 0;
    onResize = function() {
      ctx.canvas.width = this.defaults.width;
      ctx.canvas.height = this.defaults.height;
      return graph.draw(ctx);
    };
    onMouseWheel = function(e) {
      var delta;
      delta = Math.max(-1, Math.min(1, e.wheelDelta || -e.detail));
      return console.log(delta);
    };
    onMouseMoveGraph = function(e) {
      graph.move(e.clientX - startX, e.pageY - startY);
      graph.draw(ctx);
      return cursor.draw(ctx, e.clientX - graph.origin.x - 50);
    };
    onMouseMoveCursor = function(e) {
      graph.draw(ctx);
      return cursor.draw(ctx, e.clientX - 50);
    };
    onMouseDown = function(e) {
      if (e.which === 2) {
        startX = e.clientX - graph.origin.x;
        startY = e.clientY - graph.origin.y;
        window.addEventListener('mousemove', onMouseMoveGraph);
      }
      if (e.which === 1) {
        cursor.position.x = 0;
        graph.draw(ctx);
        cursor.draw(ctx, startX - 50);
        return window.addEventListener('mousemove', onMouseMoveCursor);
      }
    };
    onMouseUp = function() {
      window.removeEventListener('mousemove', onMouseMoveGraph);
      return window.removeEventListener('mousemove', onMouseMoveCursor);
    };
    window.addEventListener('resize', onResize, false);
    this.canvas.addEventListener('mousewheel', onMouseWheel, false);
    this.canvas.addEventListener('mousedown', onMouseDown, false);
    return window.addEventListener('mouseup', onMouseUp, false);
  };

  return Timeline;

})();

module.exports = Timeline;

//# sourceMappingURL=timeline.js.map
