// Generated by CoffeeScript 1.12.2
var Utils;

Utils = {
  merge: function(opts, overrides) {
    return this.extend(this.extend({}, opts), overrides);
  },
  extend: function(object, props) {
    var key, val;
    for (key in props) {
      val = props[key];
      object[key] = val;
    }
    return object;
  }
};

module.exports = Utils;

//# sourceMappingURL=utils.js.map
